
package wsimportclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailService", targetNamespace = "http://soap.webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {

    /**
     *
     * @return
     *     returns main.java.wsimportclient.ListWrapper
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservices/MailService/getAllEmailsRequest", output = "http://soap.webservices/MailService/getAllEmailsResponse")
    public ListWrapper getAllEmails();

    /**
     *
     * @param arg0
     * @return
     *     returns main.java.wsimportclient.ListWrapper
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservices/MailService/getEmailByEmailAddressRequest", output = "http://soap.webservices/MailService/getEmailByEmailAddressResponse")
    public ListWrapper getEmailByEmailAddress(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns main.java.wsimportclient.ListWrapper
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservices/MailService/getEmailBySubjectRequest", output = "http://soap.webservices/MailService/getEmailBySubjectResponse")
    public ListWrapper getEmailBySubject(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservices/MailService/addEmailRequest", output = "http://soap.webservices/MailService/addEmailResponse")
    public boolean addEmail(
        @WebParam(name = "arg0", partName = "arg0")
        Email arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservices/MailService/removeEmailRequest", output = "http://soap.webservices/MailService/removeEmailResponse")
    public boolean removeEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);



}
